### ISSUE TITLE
[Task] API 문서 작성

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#10]
### ISSUE
- Group: `SR`

### TODO
1. [x] REST API 문서 참고
2. [x] API 문서 작성
3. [x] 최종 검토 및 수정

### Labels
- Estimated time: `E: 3h`
- Group : `SR`
- Sprint: `Sprint_1`
- Urgency: `High`
