### ISSUE TITLE
[Task] 시스템 아키텍처 작성

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#11]
### ISSUE
- Group: `SR`

### TODO
1. [x] 사용할 스택 정리하기
2. [x] cloudcraft.co 활용해서 작성하기
3. [x] 최종 검토 및 수정

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `SR`
- Sprint: `Sprint_1`
- Urgency: `High`
