### ISSUE TITLE
[Task] 프로젝트 환경 설정

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#12]
### ISSUE
- Group: `SR`

### TODO
1. [x] 프로젝트 초기 환경 설정하기
2. [x] 레포지토리를 각자 포크하고 로컬에 클론하기
3. [x] 환경설정 다시한번 확인하기

### Labels
- Estimated time: `E: 2h`
- Group : `SR`
- Sprint: `Sprint_1`
- Urgency: `High`
