### ISSUE TITLE
[Task] 유효성 검사 계속 수정하기.

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#125]
### ISSUE
- Group:  `client`, `server`
- Type: `feature`

### TODO
1. [x] 모달창 위에 모달창 띄우기(부트스트랩으로는 가능한것같은데 다른 방법 찾아보기)
2. [x] 형식에 맞을때랑 안맞을때랑 구분해주기
3. [x] 에러넘버 통일 시키기

### Labels
- Estimated time: `E: ∞`
- Group : `client`, `server`
- Sprint: `Sprint_2`
- Urgency: `Low`
