### ISSUE TITLE
[Task] QnA페이지 진료과목 버튼 클릭시 해당과목 질문만 필터하기

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#159]
### ISSUE
- Group:  `client`, `server`
- Type: `feature`

### TODO
1. [x] src/modules/category.js 만들어서 진료과목 배열로 만들어놓기
2. [x] QnA페이지에서 모듈로 불러와서 map함수로 수정하기
3. [x] 각 카테고리에 온클릭함수주고 해당 카테고리 클릭시 요청보내서 필터링된 QnA불러오기

### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint_3`
- Urgency: `High`
