### ISSUE TITLE
[Task] QnA 댓글갯수 수정

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#161]
### ISSUE
- Group:  `client`
- Type: ``feature`

### TODO
1. [x] QnA페이지에 댓글갯수 상태와, 변경시킬 함수 만들기
2. [x] QnA상세페이지로 함수를 보내서 의사 답변 길이로 댓글갯수 상태 변화시켜주기
3. [x] 변화된 상태를 QnA리스트에서 적용시키기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint_3`
- Urgency: `High`
