### ISSUE TITLE
[Task] 의사 마이페이지 수정

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#178]
### ISSUE
- Group:  `client`
- Type: `bug`

### TODO
1. [x] 의사마이페이지 새로고침하면 정보 사라짐(유저마이페이지는 괜찮음)
2. [x] MY Answer CSS 깨짐 현상
3. [x] MyAnswer 답에 대한 각 질문도 같이 나오도록

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint_2`
- Urgency: `High`
