### ISSUE TITLE
[Task] 장겸

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#200]
### ISSUE
- Group:  `client`
- Type: `bug`

### TODO
1. [x] 유저마이페이지 리뷰, QnA CSS작업
2. [x] 유저마이페이지 반응형
3. [x] 병원상세페이지 병원사진 반응형 작업
4. [x] 의사 마이페이지 반응형 작업

### Labels
- Estimated time: `E: 1d`
- Group : `client`
- Sprint: `Sprint_3`
- Urgency: `High`
