### ISSUE TITLE
[Task] 예림

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#201]
### ISSUE
- Group:  `client`, `server`
- Type: `bug`

### TODO
1. [ ] 영수증 사진 없으면 리뷰 올림 방지
2. [ ] QnA목록에서 글을 올린 유저가 탈퇴하면 Kakao 유저로 나오는 부분 수정
3. [ ] 카카오 유저 마이페이지에 이메일 닉네임만 띄워주고 수정, 탈퇴 불가능으로 수정 
4. [ ] 병원상세페이지 리뷰 작성 후 리렌더링 안되는 부분 수정

### Labels
- Estimated time: `E: 1d`
- Group : `client`, `server`
- Sprint: `Sprint_3`
- Urgency: `High`
