### ISSUE TITLE
[Task] 경훈

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#202]
### ISSUE
- Group:  `client`, `server`
- Type: `bug`

### TODO
1. [x] 소셜로그인 유저는 리뷰 업로드 안되는 부분 수정
2. [x] 위치권한 한번만에 적용안되는 부분 수정
3. [x] 의사 마이페이지 회원탈퇴
4. [x] 리뷰 삭제 시 영수증 사진 같이 삭제

### Labels
- Estimated time: `E: 1d`
- Group : `server`
- Sprint: `Sprint_3`
- Urgency: `High`
