### ISSUE TITLE
[Task] 템플릿 작성

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#31]
### ISSUE
- Group:  `client`
- Type:  `feature`

### TODO
1. [x] 글로벌 스타일 컴포넌트 작성 
2. [x] 테마 별 스타일 작성 
3. [x] 각 페이지 기본 스타일 작성 

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint_2`
- Urgency: `Middle`
