### ISSUE TITLE
[Task] 일반유저 회원가입 기능 구현

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#47]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 이메일, 비밀번호 및 닉네임 유효성 검사
2. [x] 양식 입력후 일반유저 회원가입 API 요청
3. [x] 회원가입 성공 메세지
4. [x] 회원가입 후 로그인 까지 성공 시켜주기.

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint_2`
- Urgency: `High`
