### ISSUE TITLE
[Task] 의사 회원가입 기능 구현

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#48]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 이메일 및 비밀번호 유효성 검사
2. [x] 의사 회원 신청 API 요청
3. [x] 신청 완료 메세지

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint_2`
- Urgency: `High`
