### ISSUE TITLE
[Task] Sequelize 설정

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#52]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] Sequelize ORM 공식 사이트보고 Sequelize 설치하기
2. [x] Sequelize - Migrations 문서를 보고 sequelize-cli 설치하기
3. [x] Migrations 문서 보고 ORM 설정하기

### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint_2`
- Urgency: `High`
