### ISSUE TITLE
[Task] 일반유저 회원가입, 정보수정, 정보요청 구현

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#59]
### ISSUE
- Group: `server`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 일반유저 회원가입 구현
2. [x] 일반유저 정보수정 구현
3. [x] 일반유저 정보요청 구현
4. [x] 클라이언트 완성 후 테스트

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint_2`
- Urgency: `High`
