### ISSUE TITLE
[Task] 아이디어 선정 및 프로젝트 범위 설정

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#6]
### ISSUE
- Group:  `sr`

### TODO
1. [x] 프로젝트 주제 및 프로젝트 명 선정하기
2. [x] 프로젝트 범위 설정하기
3. [x] 기술 스택 및 팀 규칙 작성

### Labels
- Estimated time: `E: 3h`
- Group : `sr`
- Sprint: `Sprint_1`
- Urgency: `High`
