### ISSUE TITLE
[Task] 공통 로그인, 로그아웃, 회원탈퇴 구현

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#61]
### ISSUE
- Group:  `server`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 로그인 요청 구현
2. [x] 로그아웃 요청 구현
3. [x] 회원탈퇴 요청 구현
4. [x] 클라이언트 완성 후 테스트

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint_2`
- Urgency: `High`
