### ISSUE TITLE
[Task] 플로우차트 작성

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#8]
### ISSUE
- Group: `SR`

### TODO
1. [x] 플로우 차트 초안 작성
2. [x] 플로우차트 수정 및 보완
3. [x] 플로우차트 최종 검토

### Labels
- Estimated time: `E: 3h`
- Group : `SR`
- Sprint: `Sprint_1`
- Urgency: `High`
