### ISSUE TITLE
[Task] 지도 및 병원리스트 페이지 구성 및 기능 구현

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#80]
### ISSUE
- Group:  `client`, `server`
- Type: `feature`

### TODO
1. [x] 메인페이지에서 병원검색하러가기 버튼 클릭 시 지도에 마커를 찍어주면서 리스트 보이는 페이지로 이동
2. [x] 리스트에서 병원 클릭 시 리스트 옆에 컴포넌트로 해당 병원 상세 정보 보여주기
3. [x] 사용자의 좌표를 기준으로 근처의 병원이 나오도록 검색
4. [x] 병원상세 컴포넌트 영수증 첨부기능
5. [x] 병원상세 컴포넌트 리뷰 불러오기
6. [x] 병원상세 컴포넌트 리뷰 작성
7. [x] 병원상세 컴포넌트 의사 병원사진 업로드
8. [ ] (optional) 병원상세 컴포넌트 의사 정보수정 요청글 올리기 

### Labels
- Estimated time: `E: 1d`
- Group : `client`, `server`
- Sprint: `Sprint_3`
- Urgency: `High`
