### ISSUE TITLE
[Task] 지도 API 사용 시 사용자 위치 받아서 위치기반 서비스로 만들기

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#86]
### ISSUE
- Group: `server`
- Type: `feature`

### TODO
1. [x] 현재 사용자의 위치를 받아오기
2. [x] 검색 시 현재 위치 기준으로 근처의 병원 검색
3. [x] 리스트에대한 정보 받을 수 있는지 확인하기

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint_3`
- Urgency: `High`
