### ISSUE TITLE
[Task] DB 스키마 작성

### ISSUE THREAD

**Issue by gusdnvkfks** [codestates/Apang#9]
### ISSUE
- Group: `SR`

### TODO
1. [x] 테이블 컬럼 설정하기
2. [x] 테이블 간의 관계 설정하기
3. [x] 스키마 최종 수정 및 완성

### Labels
- Estimated time: `E: 2h`
- Group : `SR`
- Sprint: `Sprint_1`
- Urgency: `High`
